export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f7f7f7",
  colorForBackground: "#D8ECFE",
  colorForPositiveIcon: "#88AA4D",
  colorForNegativeIcon: "#F75531",
  colorForPositiveCard: "#E1EDCE",
  colorForNegativeCard: "#F8DDD7",
  colorForButton: "#FC9B27",
  colorForButtonHover: "#FC7427",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  lineHeightDefault: 1.5,
  footerHeight: "80px",
  headerHeight: "80px",
  pageWidth: "1280px"
};
